apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-info-service
  labels:
    app: external-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-info-service
  template:
    metadata:
      labels:
        app: external-info-service
    spec:
      containers:
        - name: external-info-service
          image: tripplanning-external-info-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: external-info-service-secrets
            - configMapRef:
                name: external-info-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
