apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  labels:
    app: social-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-service
  template:
    metadata:
      labels:
        app: social-service
    spec:
      containers:
        - name: social-service
          image: tripplanning-social-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: social-service-secrets
            - configMapRef:
                name: social-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
