apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestore-emulator
  labels:
    app.kubernetes.io/name: firestore-emulator
    tripplanning.io/colocate: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: firestore-emulator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firestore-emulator
        tripplanning.io/colocate: "true"
    spec:
      containers:
        - name: firestore-emulator
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
          command:
            - gcloud
            - beta
            - emulators
            - firestore
            - start
            - --host-port=0.0.0.0:8080
          ports:
            - containerPort: 8080
              name: firestore
          readinessProbe:
            tcpSocket:
              port: firestore
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: firestore
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
