apiVersion: v1
kind: Service
metadata:
  name: firestore-emulator
  labels:
    app.kubernetes.io/name: firestore-emulator
spec:
  selector:
    app.kubernetes.io/name: firestore-emulator
  ports:
    - name: firestore
      port: 8080
      targetPort: 8080
