{{- if .Values.debug.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-commander
spec:
  selector:
    app.kubernetes.io/component: redis-commander
    {{- include "tripplanning.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.debug.redisCommander.port }}
      targetPort: {{ .Values.debug.redisCommander.port }}
{{- end }}
