CREATE TABLE IF NOT EXISTS google_places (
    google_place_id VARCHAR(255) PRIMARY KEY,
    place_name VARCHAR(255) NOT NULL,
    city_name VARCHAR(255) NOT NULL,
    formatted_address CLOB,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    image_path VARCHAR(500),
    description CLOB,
    google_sub VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    destination_google_place_id VARCHAR(255),
    start_date DATE NOT NULL,
    short_description VARCHAR(80) NOT NULL,
    long_description CLOB NOT NULL,
    CONSTRAINT fk_trips_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trips_destination_google_place
        FOREIGN KEY (destination_google_place_id) REFERENCES google_places (google_place_id)
);

CREATE TABLE IF NOT EXISTS trip_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    google_place_id VARCHAR(255) NOT NULL,
    place_name VARCHAR(255) NOT NULL,
    city_name VARCHAR(255) NOT NULL,
    description CLOB,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_trip_locations_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_trip_locations_google_place
        FOREIGN KEY (google_place_id) REFERENCES google_places (google_place_id)
);

CREATE TABLE IF NOT EXISTS trip_location_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_location_id BIGINT NOT NULL,
    image_path VARCHAR(500),
    CONSTRAINT fk_trip_location_images_trip_location
        FOREIGN KEY (trip_location_id) REFERENCES trip_locations (id)
);

CREATE TABLE IF NOT EXISTS accommodation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) DEFAULT '',
    name VARCHAR(255) NOT NULL,
    google_place_id VARCHAR(255),
    city_name VARCHAR(255),
    address VARCHAR(255),
    check_in_date DATE,
    check_out_date DATE,
    cost DECIMAL(12, 2),
    currency VARCHAR(3),
    CONSTRAINT fk_accommodation_google_place
        FOREIGN KEY (google_place_id) REFERENCES google_places (google_place_id)
);

CREATE TABLE IF NOT EXISTS transport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_google_place_id VARCHAR(255),
    end_google_place_id VARCHAR(255),
    start_address VARCHAR(500),
    end_address VARCHAR(500),
    CONSTRAINT fk_transport_start_google_place
        FOREIGN KEY (start_google_place_id) REFERENCES google_places (google_place_id),
    CONSTRAINT fk_transport_end_google_place
        FOREIGN KEY (end_google_place_id) REFERENCES google_places (google_place_id)
);

CREATE TABLE IF NOT EXISTS trip_transport (
    trip_id BIGINT NOT NULL,
    transport_id BIGINT NOT NULL,
    CONSTRAINT fk_trip_transport_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_trip_transport_transport FOREIGN KEY (transport_id) REFERENCES transport (id)
);

CREATE TABLE IF NOT EXISTS trip_accommodation (
    trip_id BIGINT NOT NULL,
    accom_id BIGINT NOT NULL,
    CONSTRAINT fk_trip_accommodation_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_trip_accommodation_accommodation FOREIGN KEY (accom_id) REFERENCES accommodation (id)
);
