-- Initial schema. Derived from the JPA entity mappings via Hibernate's
-- JPA schema-generation export against PostgreSQLDialect with the Spring
-- Boot default physical-naming strategy (CamelCaseToUnderscoresNamingStrategy).
--
-- Running this once produces exactly the schema the current entities expect,
-- after which the app runs with spring.jpa.hibernate.ddl-auto=validate and
-- Flyway only applies future, forward-only migrations.

create table users (
    id          bigint generated by default as identity,
    email       varchar(320) not null unique,
    name        varchar(255) not null unique,
    image_url   varchar(500),
    description text,
    primary key (id)
);

create table trips (
    id                bigint generated by default as identity,
    user_id           bigint not null,
    title             varchar(255) not null,
    destination       varchar(255) not null,
    start_date        date not null,
    short_description varchar(80)  not null,
    long_description  text         not null,
    primary key (id)
);

create table location (
    id   bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table transport (
    id   bigint generated by default as identity,
    type varchar(50) not null,
    primary key (id)
);

create table accommodation (
    id      bigint generated by default as identity,
    type    varchar(50)  not null,
    name    varchar(255) not null,
    address varchar(255),
    primary key (id)
);

create table trip_locations (
    id          bigint generated by default as identity,
    trip_id     bigint not null,
    location_id bigint not null,
    image_url   varchar(500),
    description text,
    primary key (id)
);

create table comment (
    id         bigint generated by default as identity,
    content    text          not null,
    created_at timestamp(6)  not null,
    user_id    bigint        not null,
    trip_id    bigint        not null,
    primary key (id)
);

-- Many-to-many join tables. No surrogate PK on these, matching the JPA mapping.
create table trip_transport (
    trip_id      bigint not null,
    transport_id bigint not null
);

create table trip_accommodation (
    trip_id  bigint not null,
    accom_id bigint not null
);

create table user_likes_trips (
    user_id bigint not null,
    trip_id bigint not null
);

-- Foreign keys. Constraint names are fixed so that Hibernate's `validate` mode
-- and future Flyway migrations see deterministic identifiers instead of the
-- hash-suffixed names Hibernate would invent.
alter table trips
    add constraint fk_trips_user
    foreign key (user_id) references users (id);

alter table trip_locations
    add constraint fk_trip_locations_trip
    foreign key (trip_id) references trips (id);

alter table trip_locations
    add constraint fk_trip_locations_location
    foreign key (location_id) references location (id);

alter table comment
    add constraint fk_comment_user
    foreign key (user_id) references users (id);

alter table comment
    add constraint fk_comment_trip
    foreign key (trip_id) references trips (id);

alter table trip_transport
    add constraint fk_trip_transport_trip
    foreign key (trip_id) references trips (id);

alter table trip_transport
    add constraint fk_trip_transport_transport
    foreign key (transport_id) references transport (id);

alter table trip_accommodation
    add constraint fk_trip_accommodation_trip
    foreign key (trip_id) references trips (id);

alter table trip_accommodation
    add constraint fk_trip_accommodation_accommodation
    foreign key (accom_id) references accommodation (id);

alter table user_likes_trips
    add constraint fk_user_likes_trips_user
    foreign key (user_id) references users (id);

alter table user_likes_trips
    add constraint fk_user_likes_trips_trip
    foreign key (trip_id) references trips (id);
