CREATE TABLE tenants (
    id VARCHAR(64) PRIMARY KEY,
    slug VARCHAR(63) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    tier VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    host_url VARCHAR(512) NOT NULL,
    namespace VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE,
    db_name VARCHAR(128),
    search_index VARCHAR(128),
    firestore_database VARCHAR(128),
    gcs_bucket VARCHAR(256),
    provisioning_error TEXT,
    estimated_monthly_cost_eur DECIMAL(10, 2) NOT NULL DEFAULT 0,
    identity_platform_tenant_id VARCHAR(128),
    enabled_auth_providers TEXT,
    primary_color VARCHAR(32),
    header_title VARCHAR(255),
    icon_url VARCHAR(1024),
    frontend_path VARCHAR(256),
    image_tag VARCHAR(128),
    provisioning_steps_json TEXT
);

CREATE INDEX idx_tenants_tier ON tenants (tier);
CREATE INDEX idx_tenants_status ON tenants (status);

CREATE TABLE platform_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
