create table trip_location_images (
    id               bigint generated by default as identity,
    trip_location_id bigint not null,
    image_url        varchar(500),
    primary key (id)
);

alter table trip_location_images
    add constraint fk_trip_location_images_trip_location
    foreign key (trip_location_id) references trip_locations (id);

-- Backfill existing single-image data into the new one-to-many image table.
insert into trip_location_images (trip_location_id, image_url)
select id, image_url
from trip_locations
where image_url is not null and image_url <> '';
